### ISSUE TITLE
Subclasses and License

### ISSUE THREAD

**Issue by MattyRad** [texthtml/maybe#19]
Related to https://github.com/texthtml/maybe/issues/16

I don't know much about open source licenses, but it looks like the license in the composer.json file is  [AGPL-3.0](https://github.com/texthtml/maybe/blob/deec0f04b352bf2091069388f1c67991e66dd989/composer.json#L5) (although this repo is missing a LICENSE file which I think is required for AGPL-3.0), and some sources claim that [subclassing counts as modification](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#OOPLang).

So uh... do I have to provide hosted source code for those subclasses? Or is it possible to change the license?

**Comment by mathroc** [comment]
Err.. didn't thought about it before, but never would have guessed that subclassing would trigger that...

Anyway, changed it to MIT

**Comment by MattyRad** [comment]
Thanks!
